<?php
require_once __DIR__.'/../config/app.php';$user=require_role('admin');
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  $op=$_POST['op']??'';$pid=(int)($_POST['person_id']??0);
  if($op==='update'){$pdo->prepare('UPDATE PERSON SET name=?,phone=?,email=?,address=? WHERE person_id=?')->execute([trim($_POST['name']),trim($_POST['phone']),trim($_POST['email'])?:null,trim($_POST['address'])?:null,$pid]);flash('success','User updated.');}
  elseif($op==='delete'){if($pid===$user['person_id'])throw new RuntimeException('You cannot delete your own admin account.');$role=scalar($pdo,'SELECT role FROM AUTH_USER WHERE person_id=?',[$pid]);$pdo->beginTransaction();$pdo->prepare('DELETE FROM AUTH_USER WHERE person_id=?')->execute([$pid]);if($role==='farmer')$pdo->prepare('DELETE FROM FARMER WHERE person_id=?')->execute([$pid]);elseif($role==='driver')$pdo->prepare('DELETE FROM DRIVER WHERE person_id=?')->execute([$pid]);elseif($role==='admin')$pdo->prepare('DELETE FROM ADMIN WHERE person_id=?')->execute([$pid]);$pdo->prepare('DELETE FROM PERSON WHERE person_id=?')->execute([$pid]);$pdo->commit();flash('success','User deleted.');}
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error',$e instanceof RuntimeException?$e->getMessage():db_error_message($e));}redirect('admin/users.php');
}
$edit=null;if(isset($_GET['edit'])){$stmt=$pdo->prepare('SELECT p.*,a.role FROM PERSON p JOIN AUTH_USER a ON a.person_id=p.person_id WHERE p.person_id=?');$stmt->execute([(int)$_GET['edit']]);$edit=$stmt->fetch();}
$rows=$pdo->query('SELECT p.*,a.role,d.availability_status FROM PERSON p JOIN AUTH_USER a ON a.person_id=p.person_id LEFT JOIN DRIVER d ON d.person_id=p.person_id ORDER BY p.person_id DESC')->fetchAll();
$pageTitle='Manage Users';require __DIR__.'/../includes/header.php';
?>
<div class="page-head"><div><h1>Users</h1><p>Edit basic account information or remove unused accounts. Registration creates new users.</p></div></div>
<?php if($edit):?><div class="card" style="margin-bottom:16px"><h3>Edit <?=e(ucfirst($edit['role']))?></h3><form method="post"><input type="hidden" name="op" value="update"><input type="hidden" name="person_id" value="<?=$edit['person_id']?>"><div class="form-grid"><div class="field"><label>Name</label><input name="name" value="<?=e($edit['name'])?>" required></div><div class="field"><label>Phone</label><input name="phone" value="<?=e($edit['phone'])?>" required></div><div class="field"><label>Email</label><input name="email" value="<?=e($edit['email'])?>"></div><div class="field wide"><label>Address</label><textarea name="address"><?=e($edit['address'])?></textarea></div></div><div class="form-actions"><a class="btn btn-secondary" href="users.php">Cancel</a><button class="btn btn-primary">Save</button></div></form></div><?php endif;?>
<div class="card"><div class="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>NID</th><th>Phone</th><th>Availability</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><strong><?=e($r['name'])?></strong><small><?=e($r['email'])?></small></td><td><span class="badge"><?=e(ucfirst($r['role']))?></span></td><td><?=e($r['nid'])?></td><td><?=e($r['phone'])?></td><td><?=e($r['availability_status']?:'—')?></td><td><div class="actions"><a class="btn btn-secondary" href="?edit=<?=$r['person_id']?>">Edit</a><?php if($r['person_id']!=$user['person_id']):?><form method="post"><input type="hidden" name="op" value="delete"><input type="hidden" name="person_id" value="<?=$r['person_id']?>"><button class="btn btn-danger" data-confirm="Delete this user? Referenced farms or assignments will block deletion.">Delete</button></form><?php endif;?></div></td></tr><?php endforeach;?></tbody></table></div></div>
<?php require __DIR__.'/../includes/footer.php'; ?>
